version: '3'
services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  app:
    # some definitions
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
      # rest of the environment definitions
